### ISSUE TITLE
Proxy changeOrigin

### ISSUE THREAD

**Issue by legoheld** [txchen/light-server#72]
I tried to dockerize the light-server so i can run it with docker-compose next to my backend application.
For that I created a simple Dockerfile:
```Dockerfile
FROM node:15-alpine

RUN npm i --global light-server

ENTRYPONT [ 'light-server' ]
```

And a corresponding `docker-compse.yml`:
```yml

version: '2'

services:
  # my backend dev application
  app:
    image: ....

  reloader:
    image: light-server # the image from the above Dockerfile
    command: '-s /source -x "http://app" -w "css/**/*.css # # reloadcss" -w "js/**/*.js # # reload"'
    volumes:
      - ...:/source
    ports:
      - 4000
```

This works except the [proxy setting `changeOrigin`](https://github.com/txchen/light-server/blob/04f0e2aa7e2657a8507a92920204c8d069c28f4b/proxy.js#L10). This will rewrite all path to http://app...
If I remove that it works perfectly.

So my question is, why you added this setting?
Or can we add  proxy settings options either by env vars or cli.
